export const DECK_JS_FEATURES = `
state.filter='all';
$('connection').style.maxWidth='min(31vw,120px)';$('connection').style.overflow='hidden';$('connection').style.textOverflow='ellipsis';$('connection').style.whiteSpace='nowrap';$('connection').parentElement.style.minWidth='0';
function deckFilterMatches(item){if(state.filter==='active')return ['starting','ready','running'].includes(item.status);if(state.filter==='completed')return item.status==='completed';if(state.filter==='issues')return item.status==='failed'||item.status==='interrupted';if(state.filter==='stopped')return item.status==='stopped';return true}
renderTasks=function(){const list=$('task-list');list.replaceChildren();const visible=state.instances.filter(deckFilterMatches);if(!visible.length){const empty=document.createElement('div');empty.className='empty';empty.innerHTML='<p>'+(state.instances.length?'此筛选下没有任务':'还没有任务')+'</p>';list.append(empty)}for(const item of visible){const button=document.createElement('button');button.className='task'+(item.id===state.selected?' active':'');const title=document.createElement('strong');title.textContent=item.label||item.workspaceName;const meta=document.createElement('span');const dot=document.createElement('i');dot.className='task-state '+item.status;meta.append(dot,document.createTextNode((labels[item.status]||item.status)+' · '+item.workspaceName));button.append(title,meta);button.onclick=()=>selectTask(item.id);list.append(button)}};
$('task-filter').onchange=()=>{state.filter=$('task-filter').value;renderTasks()};
function deckRenderDevices(devices,currentId){const list=$('device-list');list.replaceChildren();if(!devices.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='没有已配对设备';list.append(empty);return}for(const device of devices){const row=document.createElement('div');row.className='device-row';const details=document.createElement('div');const name=document.createElement('strong');name.textContent=device.name+(device.id===currentId?'（当前）':'');const created=document.createElement('span');created.textContent=new Date(device.createdAt).toLocaleString();details.append(name,created);const revoke=document.createElement('button');revoke.className='danger';revoke.type='button';revoke.textContent='撤销';revoke.onclick=()=>deckRevokeDevice(device,currentId).catch(showError);row.append(details,revoke);list.append(row)}}
async function deckOpenDevices(){if($('pair-dialog').open)return;const [meResult,devicesResult]=await Promise.all([api('/api/me'),api('/api/devices')]);deckRenderDevices(devicesResult.devices,meResult.device.id);if(!$('device-dialog').open)$('device-dialog').showModal()}
async function deckRevokeDevice(device,currentId){if(!confirm('撤销设备“'+device.name+'”？'))return;await api('/api/devices/'+encodeURIComponent(device.id),{method:'DELETE',headers:{'X-Request-Id':id()}});if(device.id===currentId){$('device-dialog').close();state.events?.close();state.events=null;clearInterval(state.timer);connection('offline','未配对');$('pair-error').textContent='当前设备已撤销。请重启 Deck 后使用新的配对码。';if(!$('pair-dialog').open)$('pair-dialog').showModal();return}await deckOpenDevices()}
$('devices').onclick=()=>deckOpenDevices().catch(showError);
$('close-devices').onclick=()=>$('device-dialog').close();
$('pair-form').onsubmit=async event=>{event.preventDefault();$('pair-error').textContent='';try{await api('/api/pair',{method:'POST',headers:{'X-Request-Id':id()},body:JSON.stringify({code:$('pair-code').value,name:$('device-name').value})});location.replace('/')}catch(error){$('pair-error').textContent=error.message}};
`;
